App views PR
Javed-Shahbaz/Blog-App pull request #6
Opened 2023-08-05 20:29 UTC by Javed-Shahbaz

## In this project:
- Add the Views associated with the Models and Controllers for Blog App.
- Use preprocessed HTML files with embedded Ruby code.
- Use layouts and templates for shared content.

2023-08-05 20:46 UTC, tugsem requested changes
##  STATUS: REQUIRED CHANGES ♻️
Hello 👋 , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights 🚀 
✔️controller and views for post and user created correctly
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-05 20:46 UTC, tugsem commented on app/views/users/index.html.erb
> +            <span class="post-counter"><p class="count">Number of posts: <%= user.posts.count %></p></span>
- [ ] As per the requirement, clicking on each user must redirect us to the user show page. Kindly implement this.

2023-08-05 20:46 UTC, tugsem commented on app/views/users/show.html.erb
> +            <% @user.posts.each_with_index do |post,index|%>
- [ ] As per the requirement, only the 3 most recent posts of the user must be rendered here. Kindly implement this.
![image](https://github.com/Javed-Shahbaz/Blog-App/assets/91486791/fa1c34a6-b41e-4dfe-90ad-3c09813d45eb)
(your model)

2023-08-05 20:46 UTC, tugsem commented on app/views/users/show.html.erb
> +            <button class="all">See all posts</button>
- [ ] As per the requirement, this button must redirect to the user post index page. Kindly add this.

2023-08-05 20:46 UTC, tugsem commented on app/views/posts/index.html.erb
> +                    <% end %>
- [ ] As per the requirement, only the 5 most recent comments for the post must be rendered here. Kindly implement this.
![image](https://github.com/Javed-Shahbaz/Blog-App/assets/91486791/97d4dc5b-c218-40db-88a1-838421286ee7)
(your model)

2023-08-05 20:46 UTC, tugsem commented on app/views/posts/index.html.erb
> +                            <%= post.text %>
- [ ] Please add a link to each post that redirects users to the post show page, which you will render all of the comments for the post.

2023-08-05 23:29 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @Javed-Shahbaz , |
|Great work on making the changes requested by a previous reviewer 👏, You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. |
| <img src="https://media4.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif"/> |

## Highlights

- [ ]... ✅ Clean code
- [ ].. ✅ Green linters
- [ ].... ✅ Read me

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-05 23:29 UTC, joskalenda commented on db/migrate/20230728031306_create_users.rb
- [ ] I checked your migration files and indeed there are duplicated files for creating user, posts, and comments migration file, this cause an error on running the migration and testing your app, please make sure you keep a unique migration file for each table and resubmit your work
<img width="423" alt="1" src="https://github.com/Javed-Shahbaz/Blog-App/assets/77843050/e2803089-7597-4fb5-a0fc-4e806e2d11a5">

CreateUsers
[1](https://github.com/Javed-Shahbaz/Blog-App/pull/6/commits/ca6be6f4c6e9b37e1e50db0b0b28ae04de01cb84#diff-d6a3b454d819869879b93cd70148c678e92bd28417ff3ca1abb4e100aea3f020) and [2](https://github.com/Javed-Shahbaz/Blog-App/blob/App-Views/db/migrate/20230728152703_create_users.rb)

CreatePosts
[1]() and [2](https://github.com/Javed-Shahbaz/Blog-App/blob/App-Views/db/migrate/20230728031343_create_posts.rb)

CreateComments
[1](https://github.com/Javed-Shahbaz/Blog-App/blob/App-Views/db/migrate/20230728032028_create_comments.rb) and [2](https://github.com/Javed-Shahbaz/Blog-App/blob/App-Views/db/migrate/20230728160517_create_comments.rb)

2023-08-06 03:34 UTC, IngDavidTM approved these changes
Hi @Javed-Shahbaz 🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request follows the GitFlow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-06 03:36 UTC, merged